# Generated by Django 5.1.1 on 2024-09-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ReportCardApp", "0003_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rank",
            name="date_of_report_card_generation",
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name="rank",
            unique_together={("student_rank", "date_of_report_card_generation")},
        ),
    ]
